services:
  db:
    image: mysql:8.0
    container_name: mysql-database-lamira
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: lamira_db
    # Los puertos 3306 se eliminan para producción por seguridad y para evitar conflictos.
    # La web se conecta internamente a través de la red del contenedor.
    volumes:
      - mysql_data_lamira:/var/lib/mysql

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs-web-app-lamira
    ports:
      - "127.0.0.1:3009:3000" # Modificado para obligar a pasar por CloudPanel en puerto 3009 (para evitar choques con otros contenedores de la misma VPS)
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql://root:rootpassword@db:3306/lamira_db
      - NEXTAUTH_URL=https://lamira.online # CRÍTICO para que el login funcione en producción
      - NEXTAUTH_SECRET=news-portal-secret-key-change-in-production
      - HOSTNAME=0.0.0.0 # <-- LA SOLUCIÓN AL ERROR 502
    volumes:
      - /home/lamira/htdocs/lamira.online/public/uploads:/app/public/uploads
    restart: always

volumes:
  mysql_data_lamira: